name: .NET Build

on:
  push:
    branches:
      - main  # Este flujo de trabajo se ejecutará cuando se haga push en la rama `main`.
  pull_request:
    branches:
      - main  # También se ejecutará cuando se cree un pull request hacia `main`.

jobs:
  build:
    runs-on: ubuntu-latest  # O puedes usar windows-latest si prefieres Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      # Este paso descarga tu código en el runner de GitHub Actions.

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'  # Cambia esto por la versión de .NET que uses en tu proyecto.
    
    - name: Restore dependencies
      run: dotnet restore
      # Restaura las dependencias del proyecto (.csproj o .sln).

    - name: Build the project
      run: dotnet build --configuration Release
      # Compila el proyecto en modo `Release`.

    - name: Run unit tests
      run: dotnet test --configuration Release --no-build --verbosity normal
      # Ejecuta las pruebas unitarias. `--no-build` asegura que solo se ejecuten las pruebas sin recompilar.

    - name: Publish the project
      run: dotnet publish --configuration Release --output ./publish
      # Publica la aplicación en una carpeta `publish`.

    - name: Upload published app as artifact
      uses: actions/upload-artifact@v3
      with:
        name: published-app
        path: ./publish
      # Sube el archivo publicado como un artefacto para que puedas descargarlo después.
